"""Email alert channel for NetShield AI.

Sends HTML-formatted attack alerts to a configured recipient via
Gmail's SMTP server.  Respects a per-alterter cooldown.
"""

from __future__ import annotations

import logging
import smtplib
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

from config import Settings
from prediction.schemas import PredictionResult

logger = logging.getLogger(__name__)

_SMTP_SERVER = "smtp.gmail.com"
_SMTP_PORT = 587
_COOLDOWN_S = 300  # 5 minutes


class EmailAlerter:
    """Sends attack alerts via Gmail SMTP.

    Args:
        settings: Application settings containing email credentials.
    """

    def __init__(self, settings: Settings) -> None:
        """Initialize the email alerter.

        Args:
            settings: Application settings instance.
        """
        self._sender: str = settings.email_sender
        self._password: str = settings.email_password
        self._recipient: str = settings.email_recipient
        self._last_sent: float = 0.0

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def is_configured(self) -> bool:
        """Return ``True`` if sender, password, and recipient are all set."""
        return bool(self._sender and self._password and self._recipient)

    def test_connection(self) -> dict[str, Any]:
        """Send a test email to verify SMTP connectivity.

        Bypasses the cooldown mechanism since this is a manual test.

        Returns:
            Dictionary with keys:
                - ``configured``: bool — credentials are present.
                - ``sent``: bool — email was sent successfully.
                - ``error``: str | None — error message if any.
        """
        if not self.is_configured:
            return {
                "configured": False,
                "sent": False,
                "error": "Email sender, password, or recipient not set.",
            }

        msg = MIMEMultipart("alternative")
        msg["Subject"] = "[NetShield] Test — Email Alerts Active"
        msg["From"] = self._sender
        msg["To"] = self._recipient

        html = """\
<html>
  <body style="font-family: Arial, sans-serif; color: #333;">
    <h2 style="color: #2e7d32;">🟢 Email Alerts Active</h2>
    <p>NetShield AI email alerts are now configured and working.</p>
    <p>You will receive an email alert when an attack is detected.</p>
    <p style="color: #888; font-size: 12px; margin-top: 20px;">
      Generated by NetShield AI Intrusion Detection System
    </p>
  </body>
</html>
"""
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(_SMTP_SERVER, _SMTP_PORT) as server:
                server.starttls()
                server.login(self._sender, self._password)
                server.sendmail(self._sender, self._recipient, msg.as_string())
            logger.info("Email test message sent successfully.")
            return {
                "configured": True,
                "sent": True,
                "error": None,
            }
        except Exception as exc:  # noqa: BLE001
            logger.error("Email test failed: %s", exc)
            return {
                "configured": True,
                "sent": False,
                "error": str(exc),
            }

    def send_alert(self, result: PredictionResult) -> bool:
        """Send an email alert for an attack prediction.

        Returns early (without sending) when:
        - The sender password or recipient is empty.
        - The prediction is benign or rejected.
        - The cooldown period has not elapsed since the last send.

        Args:
            result: The PredictionResult to alert on.

        Returns:
            True if an email was sent successfully, False otherwise.
        """
        if not self._password or not self._sender or not self._recipient:
            logger.warning("Email credentials not configured; skipping alert.")
            return False

        if not result.is_attack:
            return False

        now = time.time()
        if now - self._last_sent < _COOLDOWN_S:
            logger.debug("Email alert on cooldown; skipping.")
            return False

        msg = self._build_message(result)

        try:
            with smtplib.SMTP(_SMTP_SERVER, _SMTP_PORT) as server:
                server.starttls()
                server.login(self._sender, self._password)
                server.sendmail(self._sender, self._recipient, msg.as_string())
            self._last_sent = now
            logger.info("Email alert sent for %s.", result.label)
            return True
        except Exception as exc:  # noqa: BLE001
            logger.error("Failed to send email alert: %s", exc)
            return False

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _build_message(self, result: PredictionResult) -> MIMEMultipart:
        """Build a MIME multipart message with an HTML body.

        Args:
            result: The attack prediction result.

        Returns:
            A MIMEMultipart object ready to send.
        """
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"[NetShield Alert] {result.label} Attack Detected"
        msg["From"] = self._sender
        msg["To"] = self._recipient

        ctx = result.context
        src_ip = ctx.src_ip if ctx else "unknown"
        dst_ip = ctx.dst_ip if ctx else "unknown"
        src_port = ctx.src_port if ctx else 0
        dst_port = ctx.dst_port if ctx else 0
        timestamp_str = time.strftime(
            "%Y-%m-%d %H:%M:%S UTC", time.gmtime(result.timestamp_utc)
        )

        html = f"""\
<html>
  <body style="font-family: Arial, sans-serif; color: #333;">
    <h2 style="color: #d32f2f;">⚠️ Attack Detected</h2>
    <table style="border-collapse: collapse; width: 100%;">
      <tr><td style="padding: 6px; font-weight: bold;">Attack Type</td><td style="padding: 6px;">{result.label}</td></tr>
      <tr><td style="padding: 6px; font-weight: bold;">Confidence</td><td style="padding: 6px;">{result.confidence:.2%}</td></tr>
      <tr><td style="padding: 6px; font-weight: bold;">Source IP</td><td style="padding: 6px;">{src_ip}:{src_port}</td></tr>
      <tr><td style="padding: 6px; font-weight: bold;">Destination IP</td><td style="padding: 6px;">{dst_ip}:{dst_port}</td></tr>
      <tr><td style="padding: 6px; font-weight: bold;">Time (UTC)</td><td style="padding: 6px;">{timestamp_str}</td></tr>
    </table>
    <p style="color: #888; font-size: 12px; margin-top: 20px;">
      Generated by NetShield AI Intrusion Detection System
    </p>
  </body>
</html>
"""
        msg.attach(MIMEText(html, "html"))
        return msg
